# Generated by Django 5.2.4 on 2025-07-17 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='friendship',
            new_name='idx_from_user_created',
            old_fields=('from_user', 'created_at'),
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='idx_to_user_created',
            old_fields=('to_user', 'created_at'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_from_to_user'),
        ),
    ]
