# Generated by Django 5.2.4 on 2025-08-02 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0002_rename_friendship_from_user_created_at_idx_from_user_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['from_user', 'to_user'], name='idx_from_to'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['to_user', 'from_user'], name='idx_to_from'),
        ),
    ]
