# Generated by Django 5.2.4 on 2025-07-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_likes_count'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='idx_tweet_created_at',
            old_fields=('tweet', 'created_at'),
        ),
    ]
