# Generated by Django 5.2.4 on 2025-07-17 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='like',
            new_name='idx_user_ct_id_created_at',
            old_fields=('user', 'content_type', 'content_id', 'created_at'),
        ),
        migrations.RenameIndex(
            model_name='like',
            new_name='idx_ct_id_created_at',
            old_fields=('content_type', 'content_id', 'created_at'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'content_id'), name='unique_user_content_like'),
        ),
    ]
