# Generated by Django 4.2.21 on 2025-07-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='newsfeed',
            new_name='newsfeeds_n_user_id_16c5ef_idx',
            old_fields=('user', 'created_at'),
        ),
        migrations.AddIndex(
            model_name='newsfeed',
            index=models.Index(fields=['created_at'], name='newsfeeds_n_created_13a6e0_idx'),
        ),
    ]
