# Generated by Django 4.2.21 on 2025-07-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0002_rename_newsfeed_user_created_at_newsfeeds_n_user_id_16c5ef_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='insert_tag',
            field=models.CharField(db_index=True, max_length=36, null=True),
        ),
    ]
