# Generated by Django 4.2.21 on 2025-07-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0003_newsfeed_insert_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='insert_tag',
            field=models.CharField(db_index=True, default='', max_length=36),
            preserve_default=False,
        ),
    ]
