# Generated by Django 5.2.4 on 2025-07-17 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0004_alter_newsfeed_insert_tag'),
        ('tweets', '0007_rename_tweetphoto_status_created_at_idx_status_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newsfeed',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='newsfeed',
            constraint=models.UniqueConstraint(fields=('user', 'tweet'), name='unique_user_tweet'),
        ),
    ]
