# Generated by Django 4.2.21 on 2025-07-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweetphoto'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tweet',
            new_name='tweets_twee_user_id_ba0f61_idx',
            old_fields=('user', 'created_at'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['created_at'], name='tweets_twee_created_03e7b9_idx'),
        ),
    ]
