# Generated by Django 4.2.21 on 2025-07-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_rename_tweet_user_created_at_tweets_twee_user_id_ba0f61_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='comments_count',
            field=models.IntegerField(default=0, help_text='the number of comments for the tweet'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes_count',
            field=models.IntegerField(default=0, help_text='the number of likes for the tweet'),
        ),
    ]
