# Generated by Django 4.2.21 on 2025-07-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweet_comments_count_tweet_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='the date the tweet was updated'),
        ),
    ]
