# Generated by Django 5.2.4 on 2025-07-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_tweet_updated_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tweetphoto',
            new_name='idx_status_created',
            old_fields=('status', 'created_at'),
        ),
        migrations.RenameIndex(
            model_name='tweetphoto',
            new_name='idx_tweet_order',
            old_fields=('tweet', 'order'),
        ),
        migrations.RenameIndex(
            model_name='tweetphoto',
            new_name='idx_tweet_status_deleted',
            old_fields=('tweet', 'status', 'has_deleted'),
        ),
        migrations.RenameIndex(
            model_name='tweetphoto',
            new_name='idx_deleted_created',
            old_fields=('has_deleted', 'created_at'),
        ),
        migrations.RenameIndex(
            model_name='tweetphoto',
            new_name='idx_user_created',
            old_fields=('user', 'created_at'),
        ),
    ]
