# Generated by Django 5.2.4 on 2025-07-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_rename_tweetphoto_status_created_at_idx_status_created_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tweet',
            name='tweets_twee_user_id_ba0f61_idx',
        ),
    ]
