# Generated by Django 5.2.4 on 2025-07-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_remove_tweet_tweets_twee_user_id_ba0f61_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tweet',
            name='tweets_twee_created_03e7b9_idx',
        ),
    ]
