# Generated by Django 5.2.4 on 2025-07-27 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_remove_tweet_tweets_twee_created_03e7b9_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['user', 'created_at'], name='tweets_twee_user_id_ba0f61_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['created_at'], name='tweets_twee_created_03e7b9_idx'),
        ),
    ]
