# Generated by Django 5.2.4 on 2025-08-02 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_tweet_tweets_twee_user_id_ba0f61_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['-created_at', '-id'], name='tweets_twee_created_a7441d_idx'),
        ),
    ]
