"""
Django settings for twitter project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os

import environ

env = environ.Env()

environ.Env.read_env()
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['twitter.naijizhai.com', '*']
# INTERNAL_IPS = ['10.0.2.2']
CSRF_TRUSTED_ORIGINS = ['https://twitter.naijizhai.com']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party apps
    'rest_framework',
    # "debug_toolbar",
    'django_filters',
    'notifications',

    # project apps
    'tweets',
    'friendships',
    'newsfeeds',
    'comments',
    'likes',
    'accounts',
]
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'utils.auth.CsrfExemptSessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],

}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'twitter.urls'
STATIC_URL = "static/"
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'twitter.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'twitter',
        'HOST': '0.0.0.0',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': 'yourpassword',
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,

    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
# https://www.linkedin.com/pulse/resolving-minio-behind-cloudflare-proxy-403-error-bhavesh-deshmukh-pk1nf/
# https://community.cloudflare.com/t/content-length-is-removed-on-response-of-head-method/628350?page=2
import sys

TESTING = (" ".join(sys.argv).find("manage.py test") != -1)

if TESTING:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
else:
    STORAGES = {
        # "default": {
        #     # "BACKEND": "utils.storage.CustomS3Storage",
        #     "BACKEND": "storages.backends.s3.S3Storage",
        #     "OPTIONS": {
        #         "access_key": "admin",
        #         "secret_key": "admin123",
        #         "bucket_name": "summer-project",
        #         # "endpoint_url": "http://192.168.68.73:9000",
        #         "region_name": "us-east-1",
        #         "addressing_style": "path",
        #         # "signature_version": "s3v4",
        #         # "use_ssl": True,
        #         # "verify": True,
        #     }
        # },
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": "twitter-bucket-naijizhai",
                "region_name": "us-east-2",
                "signature_version": "s3v4",
                # "access_key": "aws configure/awscli",
                # "secret_key": "",
            }
        },

        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        }
    }

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

# LOGGING = {
#     'version': 1,
#     'filters': {
#         'require_debug_true': {
#             '()': 'django.utils.log.RequireDebugTrue',
#         },
#     },
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'filters': ['require_debug_true'],
#             'class': 'logging.StreamHandler',
#         }
#     },
#     'loggers': {
#         'django.db.backends': {
#             'level': 'DEBUG',
#             'handlers': ['console'],
#         }
#     }
# }

# https://github.com/jazzband/django-redis
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'TIMEOUT': 86400,  # 1 day
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'testing': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/2',
        'TIMEOUT': 86400,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'testing',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'breakfast-cache-sync': {
        'task': 'newsfeeds.tasks.batch_sync_active_users_cache',
        'schedule': crontab(hour=7, minute=0),  # before breakfast
    },
    'lunch-cache-sync': {
        'task': 'newsfeeds.tasks.batch_sync_active_users_cache',
        'schedule': crontab(hour=11, minute=0),  # before lunch
    },
    'dinner-cache-sync': {
        'task': 'newsfeeds.tasks.batch_sync_active_users_cache',
        'schedule': crontab(hour=16, minute=0),  # before dinner
    },
}

CELERY_TIMEZONE = 'UTC'

# Celery for MQ
CELERY_BROKER_URL = 'sqs://'
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'region': 'us-east-2',
    'visibility_timeout': 30,
    'wait_time_seconds': 20,
}
from kombu import Queue

# celery -A twitter worker -Q PriorityQueue.fifo,Twitte_Queue.fifo --loglevel=info
CELERY_TASK_QUEUES = (
    Queue('Standard', routing_key='NewsFeed'),
    Queue('HighPriority', routing_key='HighPriority'),
)

CELERY_TASK_ALWAYS_EAGER = TESTING
CELERY_RESULT_BACKEND = 'redis://localhost:6379/8'

BROKER_TRANSPORT_OPTIONS = {
    'region': 'us-east-2',
    'polling_interval': 1,
    'wait_time_seconds': 10,
}

RATELIMIT_REDIS_HOST = 'localhost'
RATELIMIT_REDIS_PORT = 6379
RATELIMIT_REDIS_DB = 11
RATELIMIT_ENABLE = not TESTING

OPENAI_API_KEY = env('OPENAI_API_KEY', default='your-api-key-here')

# custom thresholds
CONTENT_MODERATION_THRESHOLDS = {
    'hate': 0.6,
    'harassment': 0.7,
    'violence': 0.8,
    'self-harm': 0.5,
    'sexual': 0.7,
    'sexual/minors': 0.3,
}
